base_dir: /Users/markun/git/rsna2024/kaggle/data
input_dir: /Users/markun/git/rsna2024/kaggle
output_dir: /Users/markun/git/rsna2024/kaggle/outputs
image_dir: /Users/markun/git/rsna2024/kaggle/data
submission_dir: /Users/markun/git/rsna2024/kaggle/outputs