base_dir: /Users/markun/git/rsna2024/kaggle/
input_dir: /Users/markun/git/rsna2024/kaggle/data
output_dir: /Users/markun/git/rsna2024/kaggle/outputs
image_dir: /Users/markun/git/rsna2024/kaggle/data/cvt_png
submission_dir: /Users/markun/git/rsna2024/kaggle/outputs