hydra:
  job:
    name: inference
    chdir: true
  run:
    dir: ${directory.output_dir}/${hydra.job.name}/${hydra.job.override_dirname}
  sweep:
    dir: ${directory.output_dir}/${hydra.job.name}
    subdir: ${hydra.job.override_dirname}

defaults:
  - _self_
  - directory: local
  - common: label
  - dataset: rsna24_v1
  - model: convnextv2
  - split: fold_0

env: local
exp_name: dummy
debug: true
wandb: offline
num_folds: 5
batch_size: 1
seed: 42

inferencer:
  use_amp: true
  num_workers: os.cpu_count()
