conditions:
  - 'spinal_canal_stenosis'
  - 'left_neural_foraminal_narrowing' 
  - 'right_neural_foraminal_narrowing'
  - 'left_subarticular_stenosis'
  - 'right_subarticular_stenosis'

levels:
  - 'l1_l2'
  - 'l2_l3'
  - 'l3_l4'
  - 'l4_l5'
  - 'l5_s1'

label2id:
  'Normal/Mild': 0
  'Moderate': 1
  'Severe': 2