conditions:
  - 'Spinal Canal Stenosis'
  - 'Left Neural Foraminal Narrowing'
  - 'Right Neural Foraminal Narrowing'
  - 'Left Subarticular Stenosis'
  - 'Right Subarticular Stenosis'

levels:
  - 'L1/L2'
  - 'L2/L3'
  - 'L3/L4'
  - 'L4/L5'
  - 'L5/S1'

label2id:
  'Normal/Mild': 0
  'Moderate': 1
  'Severe': 2