conditions:
  - 'spinal_canal_stenosis'
  - 'left_neural_foraminal_narrowing' 
  - 'right_neural_foraminal_narrowing'
  - 'left_subarticular_stenosis'
  - 'right_subarticular_stenosis'

levels:
  - 'L1/L2'
  - 'L2/L3'
  - 'L3/L4'
  - 'L4/L5'
  - 'L5/S1'

label2id:
  'Normal/Mild': 0
  'Moderate': 1
  'Severe': 2